version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 
  pre_build:
    commands:
      - npm install
  build:
    commands: 
      - npm run build 
  post_build:
    commands:
      - aws s3 rm s3://frontend-teamsynergy/ --recursive
      - aws s3 cp build/ s3://frontend-teamsynergy/ --recursive